### ISSUE TITLE
请求新增 回调

### ISSUE THREAD

**Issue by SrcSync** [ptwxhq/EasyCefUI#2]
请求新增
window.SetCallback("OnWorkSuccess", function(a, b) { ... }); 方法，C++侧执行完毕某操作后可利用回调通知 JS

另外有什么方法可以更好的将用户类中的数据暴露给 JS直接通过属性 赋值、取值，例如wke中的jsData，通过传递类指针的方式

**Comment by ptwxhq** [comment]
回调的话建议在本地直接注册一个专门的函数并在里面调用JS，如果大量使用的话可以把信息都放参数里再包一层。
为了不太过于复杂，暂时不考虑支持更多数据类型，有需要的话可以转为json字符串后传递
